name: Build pages by MkDocs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout master
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install pipenv
      run: python -m pip install --upgrade pipenv wheel
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.local/share/virtualenvs
          ~/.cache/pip
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pipenv-
          ${{ runner.os }}
    - name: Install dependencies
      run: pipenv sync      # Installs all packages specified in Pipfile.lock.
    - name: Build website
      run: pipenv run mkdocs build --site-dir public
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.8.0
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public